stages:
  - clean
  - test
  - package
  - deploy

clean:
  stage: clean
  script:
    - 'mvn clean'
  only:
    - master

test:
  stage: test
  script:
    - 'mvn test'
  only:
    - master

package:
  stage: package
  script:
    - 'mvn package -DskipTests'
  only:
    - master

deploy:
  stage: deploy
  script:
    - 'copy C:\dev\repos\git\ProjectJavaIntegration_FrontEnd\target\jfx\native\IntegrationProject-1.0.exe \\DESKTOP-D95UF8T\deploy'
  only:
    - master  
