variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=C:/Users/gabri/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true
    
cache:
  paths:
    - .m2/repository

stages:
  - clean
  - test
  - package
  - deploy

clean:
  stage: clean
  script:
    - 'mvn clean'
  only:
    - master

test:
  stage: test
  script:
    - 'mvn test'
  only:
    - master

package:
  stage: package
  script:
    - 'mvn package -DskipTests'
  only:
    - master

deploy:
  stage: deploy
  script:
    - 'copy C:\dev\repos\git\ProjectJavaIntegration_FrontEnd\target\jfx\native\IntegrationProject-1.0.exe \\DESKTOP-D95UF8T\deploy'
  only:
    - master  
