stages:
  - clean
  - test
  - package
  - deploy

clean:
  stage: clean
  script:
    - echo $JAVA_HOME  
    - mvn clean
  only:
    - master

test:
  stage: test
  script:
    - echo $JAVA_HOME  
    - mvn test
  only:
    - master

package:
  stage: package
  script:
    - echo $JAVA_HOME  
    - mvn package -DskipTests
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo $JAVA_HOME  
    - copy C:\dev\repos\git\ProjectJavaIntegration_FrontEnd\target\jfx\native\IntegrationProject-1.0.exe \\DESKTOP-D95UF8T\deploy
  only:
    - master  
