variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true
    
cache:
  paths:
    - .m2/repository

stages:
  - clean
  - test
  - package

clean:
  stage: clean
  script:
    - 'mvn clean'
  only:
    - develop

test:
  stage: test
  script:
    - 'mvn test'
  only:
    - develop

package:
  stage: package
  script:
    - 'mvn package -DskipTests'
  only:
    - develop
